version: "3"
services:
  web:
    build: .
    links:
      - db
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=flaskblog
    volumes:
      - ./data:/var/lib/mysql
  frontend:
    image: "nginx"
    ports:
      - "8080:80"
    links:
      - web
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/conf:/etc/nginx/conf.d
      - ./frontend/log:/var/log/nginx
