"""empty message

Revision ID: 1fc89ca7cdc2
Revises: ca9b1276a92b
Create Date: 2018-01-03 22:53:34.794817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc89ca7cdc2'
down_revision = 'ca9b1276a92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'user', ['name'], unique=True)
    # ### end Alembic commands ###
