"""empty message

Revision ID: ca9b1276a92b
Revises: 848bcbcfa119
Create Date: 2018-01-03 15:18:57.784881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9b1276a92b'
down_revision = '848bcbcfa119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('image', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'image', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'user_id')
    op.drop_column('image', 'post_id')
    # ### end Alembic commands ###
