"""empty message

Revision ID: e1260fe594fe
Revises: 1fc89ca7cdc2
Create Date: 2018-01-04 19:09:47.808458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1260fe594fe'
down_revision = '1fc89ca7cdc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_ibfk_2', 'image', type_='foreignkey')
    op.drop_column('image', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('image_ibfk_2', 'image', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
